### ISSUE TITLE
How can I get this DWT picture?

### ISSUE THREAD

**Issue by Carry-w** [Alik033/ML-CrAIST#1]
Thank you very much for your work.
I would like to know how you obtained the 1-level DWT and 2-level DWT images here.
What should I do to obtain  two-level DWT related images of another example image?
If you could tell me, thank you very much.
![ML_CrIAST-diagram](https://github.com/user-attachments/assets/d3a66ae9-94e1-4249-a472-f1aba0f10b97)

**Comment by Alik033** [comment]
Thanks for showing interest in ML-CrAIST.

Please refer to the DWT_visualisation folder for visualization. Change the input image depending on how much depth you want to go. For example, if you want to go to a 2-level DWT, your input will be the LL of the 1-level DWT.
